name: 'Create e2e comment'
description: 'Create e2e comment'
inputs:
  token:
    description: 'GitHub token'
    required: true
  repo_name:
    description: "Repository name"
    required: true
  commit_hash:
    description: 'Commit hash'
    required: true
  run_id:
    description: 'e2e run id for target link'
    required: true
  issue:
    description: 'Issue ID'
    required: true
outputs:
  comment_id:
    description: "Comment ID"
    value: ${{ steps.create_comment.outputs.id }}
runs:
  using: "composite"
  steps:
    - name: Create or update comment
      id: create_comment
      run: |
        COMMENTS=$(curl \
        -H "Accept: application/vnd.github.v3+json" -H 'Authorization: token '"$GITHUB_TOKEN" \
        https://api.github.com/repos/Chili-Piper/'"$REPO_NAME"'/issues/$ISSUE/comments)
        
        for k in $(jq 'keys | .[]' <<< "$COMMENTS"); do
          value=$(jq -r ".[$k]" <<< "$COMMENTS");
          body=$(jq -r '.body' <<< "$value");
        
          if [[ $body == *"e2e run"* ]]
          then
            COMMENT_ID=$(jq -r '.id' <<< "$value");
            break
          fi
        done
        
        if (( $COMMENT_ID ))
        then
          echo FOUND COMMENT. ID=$COMMENT_ID
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json"  -H 'Authorization: token '"$GITHUB_TOKEN" \
          https://api.github.com/repos/Chili-Piper/'"$REPO_NAME"'/issues/comments/$COMMENT_ID \
          -d '{"body":"âš™ e2e run in progress\r\n| Name  | Info |\r\n| ---- | ---- |\r\n| âš™ status | In progress |\r\n| ðŸ”¨ Latest commit | https://github.com/Chili-Piper/'"$REPO_NAME"'/commit/'"$COMMIT_HASH"' |\r\n| ðŸ” Latest run | https://github.com/Chili-Piper/e2e/actions/runs/'"$RUN_ID"' |"}'
        else
          COMMENT_RES=$(curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json"  -H 'Authorization: token '"$GITHUB_TOKEN" \
          https://api.github.com/repos/Chili-Piper/'"$REPO_NAME"'/issues/$ISSUE/comments \
          -d '{"body":"âš™ e2e run in progress\r\n| Name  | Info |\r\n| ---- | ---- |\r\n| âš™ status | In progress |\r\n| ðŸ”¨ Latest commit | https://github.com/Chili-Piper/'"$REPO_NAME"'/commit/'"$COMMIT_HASH"' |\r\n| ðŸ” Latest run | https://github.com/Chili-Piper/e2e/actions/runs/'"$RUN_ID"' |"}')
        
          echo COMMENT_RES = $COMMENT_RES
          echo ID STRINGS = $(echo $COMMENT_RES | grep -o '"id": [^,]*')
          echo FIRST ID STRING = $(echo $COMMENT_RES | grep -o '"id": [^,]*' | head -1)
          echo FIRST ID = $(echo $COMMENT_RES | grep -o '"id": [^,]*' | head -1 | grep -o '[0-9]*$')
          COMMENT_ID=$(echo $COMMENT_RES | grep -o '"id": [^,]*' | head -1 | grep -o '[0-9]*$')
        
          echo NEW COMMENT IS CREATED. ID=$COMMENT_ID
        fi
        
        echo "::set-output name=id::$(echo $TRAFFIC)"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        REPO_NAME: ${{ inputs.repo_name }}
        COMMIT_HASH: ${{ inputs.commit_hash }}
        RUN_ID: ${{ inputs.run_id }}
        ISSUE: ${{ inputs.issue }}
      shell: bash
