name: 'Set up'
description: 'Set up environment'
inputs:
  ref:
    description: 'Ref for checkout'
    required: false
  fetch-depth:
    description: 'Fetch depth for checkout'
    required: false
  npm_token:
    description: 'NPM token'
    required: false
  full_install:
    description: 'Run yarn with --ignore-optional --production=false flags'
    required: false
  cache_path:
    description: 'Path variable sent to cache action'
    required: false
    default: node_modules
  custom_install:
    description: 'Use custom params for install dependencies'
    required: false
  cache:
    description: 'If need to cache dependencies'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        # https://github.com/facebook/jest/issues/11956
        node-version: '16.10.0'

    - name: Install yarn
      run: corepack enable
      shell: bash

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Cache node_modules
      if: inputs.cache == 'true'
      uses: actions/cache@v3
      id: node-modules-cache
      env:
        cache-name: node-modules-yarn
        cache-fingerprint: ${{ env.node-version }}-${{ hashFiles('**/yarn.lock') }}
      with:
        path: ${{ inputs.cache_path }}
        key: v4-${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}
        restore-keys: v4-${{ runner.os }}-${{ env.cache-name }}-

    - name: NPM auth
      if: ${{ inputs.npm_token }}
      run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      env:
        NPM_TOKEN: ${{ inputs.npm_token }}
      shell: bash

    - name: Yarn berry NPM auth
      if: ${{ inputs.npm_token }}
      run: yarn config set 'npmRegistries["//registry.npmjs.org"].npmAuthToken' "${NPM_TOKEN}"

    - name: Install dependencies
      if: (inputs.cache == 'false' || steps.node-modules-cache.outputs.cache-hit != 'true') && ! inputs.full_install
      run: yarn --immutable
      shell: bash

    - name: Install dependencies FULL
      if: (inputs.cache == 'false' || steps.node-modules-cache.outputs.cache-hit != 'true') && inputs.full_install
      run: yarn --immutable --ignore-optional --production=false
      shell: bash
