name: "Integration Checks"
description: "Checks for FE <-> BE Integration"
inputs:
  frontend:
    description: "Frontend apps versions"
    required: false
  backend:
    description: "Backend services versions"
    required: false
  gcloud_credentials_json:
    description: "GCLOUD credentials"
    required: true
  checkout_token:
    description: "Github Token"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup
      uses: Chili-Piper/frontend-actions/.github/actions/frontend-repo-setup@integration-checks
      with:
        checkout_path: api-client-source
        checkout_repo: Chili-Piper/frontend
        checkout_token: ${{ inputs.checkout_token }}
    - name: Authenticate to CPCLOUD
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.gcloud_credentials_json }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Update api-client services.json
      uses: Chili-Piper/frontend-actions/.github/actions/integration-checks/update-be-services@integration-checks
      with:
        backend: |
          customization-settings: v0.0.21
          concierge-fire: 0.55.296
