name: 'Tag version'
description: 'Update version and create tag'
inputs:
  github_token:
    description: "GitHub token"
    required: true
  git_email:
    description: "Git email"
    required: false
    default: "SRE ChiliPiper Committer"
  git_name:
    description: "Git name"
    required: false
    default: "sre+bot@chilipiper.com"
  repo_name:
    description: 'Repository name'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
      with:
        # https://github.com/facebook/jest/issues/11956
        node-version: '16.10.0'
    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
        token: ${{ inputs.github_token }}
    - name: Get traffic
      id: get_traffic
      run: |
        git config --global user.email "$GIT_EMAIL"
        git config --global user.name "$GIT_NAME"
        git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/Chili-Piper/$REPO_NAME
        npm version patch -m "[skip ci] CPP-0 - Version: %s" --no-commit-hooks;
        git push && git push origin --tags;
        echo new_tag=$(git describe --tags) >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GIT_NAME: ${{ inputs.git_name }}
        GIT_EMAIL: ${{ inputs.git_email }}
        REPO_NAME: ${{ inputs.repo_name }}
      shell: bash
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.get_traffic.outputs.new_tag }}
        name: Release ${{ steps.get_traffic.outputs.new_tag }}
        token: ${{ inputs.github_token }}
        repo: ${{ inputs.repo_name }}
