name: 'Update e2e comment'
description: 'Update e2e comment'
inputs:
  token:
    description: 'GitHub token'
    required: true
  repo_name:
    description: "Repository name"
    required: true
  commit_hash:
    description: 'Commit hash'
    required: true
  run_id:
    description: 'e2e run id for target link'
    required: true
  comment_id:
    description: 'Comment ID'
    required: true
  status:
    description: 'e2e run status (success|failure)'
    required: true
  dashboard_url:
    description: 'Cypress dashboard URL'
    required: false
runs:
  using: "composite"
  steps:
    - name: Update comment
      run: |
        HEADER_LINE='\r\n| Name  | Info |\r\n| ---- | ---- |'
        COMMIT_LINE='\r\n| 🔨 Latest commit | https://github.com/Chili-Piper/'$REPO_NAME'/commit/'$COMMIT_HASH' |'
        RUN_LINE='\r\n| 🔍 Latest run | https://github.com/Chili-Piper/e2e/actions/runs/'$RUN_ID' |'
        if (( $DASHBOARD_URL ))
        then
          DASHBOARD_LINE='\r\n| 📝 Cypress dashboard | '$DASHBOARD_URL' |'
        fi

        if [[ $STATUS == 'success' ]]
        then
          COMMENT_LINE='✅ e2e run succeeded'
          STATUS_LINE='\r\n| ✅ status | Success |'
        else
          COMMENT_LINE='❌ e2e run failed'
          STATUS_LINE='\r\n| ❌ status | Fail |'
        fi
        
        DATA='{"body":"'$COMMENT_LINE$HEADER_LINE$STATUS_LINE$COMMIT_LINE$RUN_LINE$DASHBOARD_LINE'"}'
        
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json"  -H 'Authorization: token '$GITHUB_TOKEN \
          https://api.github.com/repos/Chili-Piper/$REPO_NAME/issues/comments/$COMMENT_ID \
          -d "$DATA"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        REPO_NAME: ${{ inputs.repo_name }}
        COMMIT_HASH: ${{ inputs.commit_hash }}
        RUN_ID: ${{ inputs.run_id }}
        COMMENT_ID: ${{ inputs.comment_id }}
        STATUS: ${{ inputs.status }}
        DASHBOARD_URL: ${{ inputs.dashboard_url }}
      shell: bash
