name: 'Update e2e comment'
description: 'Update e2e comment'
inputs:
  token:
    description: 'GitHub token'
    required: true
  repo_name:
    description: "Repository name"
    required: true
  commit_hash:
    description: 'Commit hash'
    required: true
  run_id:
    description: 'e2e run id for target link'
    required: true
  comment_id:
    description: 'Comment ID'
    required: true
  status:
    description: 'e2e run status (success|failure)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Update comment
      run: |
        if [[ $STATUS == 'success' ]]
        then
          DATA='{"body":"✅ e2e run succeeded\r\n| Name  | Info |\r\n| ---- | ---- |\r\n| ✅ status | Success |\r\n| 🔨 Latest commit | https://github.com/Chili-Piper/'"$REPO_NAME"'/commit/'"$COMMIT_HASH"' |\r\n| 🔍 Latest run | https://github.com/Chili-Piper/e2e/actions/runs/'"$RUN_ID"' |"}'
        else
          DATA='{"body":"❌ e2e run failed\r\n| Name  | Info |\r\n| ---- | ---- |\r\n| ❌ status | Fail |\r\n| 🔨 Latest commit | https://github.com/Chili-Piper/'"$REPO_NAME"'/commit/'"$COMMIT_HASH"' |\r\n| 🔍 Latest run | https://github.com/Chili-Piper/e2e/actions/runs/'"$RUN_ID"' |"}'
        fi
        
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json"  -H 'Authorization: token '"$GITHUB_TOKEN" \
          https://api.github.com/repos/Chili-Piper/'"$REPO_NAME"'/issues/comments/$COMMENT_ID \
          -d "$DATA"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        REPO_NAME: ${{ inputs.repo_name }}
        COMMIT_HASH: ${{ inputs.commit_hash }}
        RUN_ID: ${{ inputs.run_id }}
        COMMENT_ID: ${{ inputs.comment_id }}
        STATUS: ${{ inputs.status }}
      shell: bash
