name: "Deploy to k8s"
description: "Deploy to k8s"
inputs:
  credentials_json:
    description: "Credentials JSON for GCloud"
    required: true
  project_name:
    description: "Project name"
    required: false
  target_env:
    description: "Target environment"
    required: false
  build_args:
    description: "Build args"
    required: false
  working_directory:
    description: "Working Directory"
    required: false
  skip_gcloud_auth:
    description: "In case the workflow already authenticates to gcloud for some reason, this prevents double auth bug"
    required: false
runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      if: ${{ inputs.skip_gcloud_auth != 'true' }}
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.credentials_json }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Authenticate to Docker Registry
      shell: bash
      run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin us-central1-docker.pkg.dev
    - name: Setup env
      run: |
        export VERSION=$( node -p -e "require('./package.json').version" )
        export IMAGE="us-central1-docker.pkg.dev/chilipiper-cloud/apps/$PROJECT_NAME:${VERSION}"

        echo VERSION=$VERSION >> $GITHUB_ENV
        echo IMAGE=$IMAGE >> $GITHUB_ENV
      env:
        PROJECT_NAME: ${{ inputs.project_name }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - name: Build & push docker image
      run: |
        docker build ${{ inputs.build_args }} -f "./Dockerfile" -t "$IMAGE" .
        docker push $IMAGE
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - name: Deploy to docker registry with env tag
      if: ${{ inputs.target_env == 'staging' }}
      run: |
        export IMAGEWithEnv="us-central1-docker.pkg.dev/chilipiper-cloud/apps/$PROJECT_NAME:${VERSION}-$TARGET_ENV"
        docker tag "$IMAGE" "$IMAGEWithEnv"
        docker push $IMAGEWithEnv

        echo "Deployed to $TARGET_ENV"
      env:
        TARGET_ENV: ${{ inputs.target_env }}
        PROJECT_NAME: ${{ inputs.project_name }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
