name: 'Dispatch e2e run'
description: 'Dispatch e2e run'
inputs:
  token:
    description: 'GitHub token'
    required: true
  repo_name:
    description: 'Repo name. In case if you need to create a status check and a comment'
    required: false
  commit_sha:
    description: "Commit hash. In case if you need to create a status check and a comment"
    required: false
  issue:
    description: 'Issue number. In case if you need to create a comment'
    required: false
  branch:
    description: 'Preferred branch to run tests instead of main'
    required: false
  homebase_url:
    description: 'Homebase URL'
    required: false
  ib_url:
    description: 'Instant-booker URL'
    required: false
  concierge_url:
    description: 'Concierge URL'
    required: false
  event:
    description: "Dispatched event (e2e_call|ib_e2e_call)"
    required: false
  environment:
    required: false
    description: Select environment to run tests
  additionalTags:
    required: false
    description: Add additional tags, comma separated
  skip3rdparty:
    required: false
    description: Skip 3rd party
  skipIb:
    required: false
    description: Skip Instant Booker
  skipChat:
    required: false
    description: Skip Chat
  skipChiliCal:
    required: false
    description: Skip ChiliCal
  skipConcierge:
    required: false
    description: Skip Concierge
  skipIntegrations:
    required: false
    description: Skip Integartions
  skipPlatform:
    required: false
    description: Skip Platform
  skipUnsorted:
    required: false
    description: Skip Unsorted
runs:
  using: "composite"
  steps:
    - name: CALL E2E
      run: |
        echo CALL E2E RUN
        curl -X POST https://api.github.com/repos/Chili-Piper/e2e/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Authorization: token '$GITHUB_TOKEN \
        --data '{"event_type": "full_e2e", "client_payload": ${{ toJson(inputs) }}}'
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        REPO_NAME: ${{ inputs.repo_name }}
        COMMIT_SHA: ${{ inputs.commit_sha }}
        ISSUE: ${{ inputs.issue }}
        BRANCH: ${{ inputs.branch }}
        HOMEBASE_URL: ${{ inputs.homebase_url }}
        IB_URL: ${{ inputs.ib_url }}
        CONCIERGE_URL: ${{ inputs.concierge_url }}
      shell: bash
