name: 'Set up'
description: 'Set up environment'
inputs:
  fetch-depth:
    description: 'Fetch depth for checkout'
    required: false
  github_token:
    description: 'github_token'
    required: false
outputs:
  LATEST_TAG:
    description: "Latest tag"
    value: ${{ steps.latest_tag.outputs.LATEST_TAG }}
runs:
  using: 'composite'
  steps:
    - name: Setup
      uses: Chili-Piper/frontend-actions/.github/actions/setup@CPP-0-cache2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        cache_path: |
          **/node_modules
          !**/node_modules/.cache/turbo
          .yarn/cache
    - name: set LATEST_TAG
      if: inputs.fetch-depth == '0'
      id: latest_tag
      run: |
          LATEST_TAG=$(git describe --abbrev=0 --tags)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
      shell: bash
