name: 'Update description'
description: 'Update GitHub PR description based on template'
inputs:
  token:
    description: "GitHub token"
    required: true
  head-branch-regex:
    description: "Head branch regexp"
    required: true
  body-template:
    description: 'Body template'
    required: true
  body-template-regex:
    description: 'Body template reg exp'
    required: true
runs:
  using: "node16"
  main: 'dist/index.js'
